### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionError: HTTPSConnectionPool(host='none', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2474e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

### ISSUE THREAD

**Issue by LOn5Ghz** [markopolo123/discord-proxmox-bot#2]
Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb2474e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='none', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2474e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/discord-proxmox-bot/main.py", line 92, in status
    vm = ProxmoxVM(config)
  File "/home/pi/discord-proxmox-bot/main.py", line 27, in __init__
    self.proxmox = proxmoxer.ProxmoxAPI(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/core.py", line 210, in __init__
    self._backend = importlib.import_module(f".backends.{backend}", "proxmoxer").Backend(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 302, in __init__
    self.auth = ProxmoxHTTPAuth(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 59, in __init__
    self._get_new_tokens(password=password, otp=otp)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 70, in _get_new_tokens
    response_data = requests.post(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2474e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionError: HTTPSConnectionPool(host='none', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2474e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

**Comment by markopolo123** [comment]
@LOn5Ghz looks like you've not got a working connection to your proxmox host:

`Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

**Comment by LOn5Ghz** [comment]
Hm? Maybe I haven't set it in the right format? Would you provide me with the right format? I used my servers url

**Comment by markopolo123** [comment]
```
export VMID="111"
export PVE_PASSWORD="passwordhere"
export PVE_USERNAME="root@pam"
export PVE_NODE="pve"
export PVE_URL="pve.internal.sharpley.xyz"
export DISCORD_TOKEN="tokenhere"
```

**Comment by markopolo123** [comment]
note that I am using a valid cert, if you are not you'll need to edit [this line](https://github.com/markopolo123/discord-proxmox-bot/blob/ad0ea0111791e454d45b41ee9738ef39f76b78c4/main.py#L31) :)

**Comment by LOn5Ghz** [comment]
So to clarify, I use the above variables in the python file? I'm not too great with code and thank you for the fast replies I needed this badly

**Comment by LOn5Ghz** [comment]
i also set ssl cert to false to avoid any issues

**Comment by markopolo123** [comment]
no worries, 
these are the commands you'll need to get it running:

```bash
# get the code:
git clone git@github.com:markopolo123/discord-proxmox-bot.git

# change directory
cd discord-proxmox-bot

# configure the python env and install packages: 
poetry install

# set your environment variables:
export VMID="111"
export PVE_PASSWORD="passwordhere"
export PVE_USERNAME="root@pam"
export PVE_NODE="pve"
export PVE_URL="pve.internal.sharpley.xyz"
export DISCORD_TOKEN="tokenhere"

# run the bot:
poetry run python main.py
```

**Comment by LOn5Ghz** [comment]
my issue is where to put said env variables

**Comment by LOn5Ghz** [comment]
import proxmoxer
from pydantic import BaseModel
import discord
from discord.ext import commands
import os

# Define the configuration data for the ProxmoxVM object
config_data = {
    "hostname": f'{os.getenv("https://192.168.1.148:8006/#")}',
    "username": f'{os.getenv("root@pam")}',
    "password": f'{os.getenv("passwdhere")}',
    "node": f'{os.getenv("pve")}',
    "vm_id": f'{os.getenv("101")}',
}


class ProxmoxVMConfig(BaseModel):
    hostname: str
    username: str
    password: str
    node: str
    vm_id: str


class ProxmoxVM:
    def __init__(self, config: ProxmoxVMConfig):
        self.proxmox = proxmoxer.ProxmoxAPI(
            config.hostname,
            user=config.username,
            password=config.password,
            verify_ssl=False,
        )
        self.vm = self.proxmox.nodes(config.node).qemu(config.vm_id)

    def start(self):
        self.vm.status.post("start")

    def shutdown(self):
        self.vm.status.post("shutdown")

    def status(self):
        status_dict = self.vm.status.current.get()
        return status_dict


DISCORD_TOKEN ="TOKEN HERE"
intents = discord.Intents.default()
intents.message_content = True
intents.typing = False
intents.presences = False
bot = commands.Bot(command_prefix="$", intents=intents)


@bot.command()
async def shutdown(ctx):
    # Create a ProxmoxVMConfig object from the configuration data
    config = ProxmoxVMConfig(**config_data)
    # Create a ProxmoxVM object from the configuration
    vm = ProxmoxVM(config)
    state = vm.status()
    if state["status"] == "stopped":
        message = "server already stopped"
        await ctx.channel.send(f"{message}")
    else:
        vm.shutdown()
        message = "server shutting down"
        await ctx.channel.send(f"{message}")


@bot.command()
async def start(ctx):
    # Create a ProxmoxVMConfig object from the configuration data
    config = ProxmoxVMConfig(**config_data)
    # Create a ProxmoxVM object from the configuration
    vm = ProxmoxVM(config)
    state = vm.status()
    if state["status"] == "running":
        message = "server already running"
        await ctx.channel.send(f"{message}")
    else:
        vm.start()
        message = "server started"
        await ctx.channel.send(f"{message}")


@bot.command()
async def status(ctx):
    # Create a ProxmoxVMConfig object from the configuration data
    config = ProxmoxVMConfig(**config_data)

    # Create a ProxmoxVM object from the configuration
    vm = ProxmoxVM(config)
    state = vm.status()
    await ctx.channel.send(f"🚀 Server Status: {state['status']}")


bot.run(DISCORD_TOKEN)

**Comment by markopolo123** [comment]
use a tool like [direnv](https://direnv.net). Once installed create a file called `.envrc` in the bot folder and inside put 
```bash
export VMID="111"
export PVE_PASSWORD="passwordhere"
export PVE_USERNAME="root@pam"
export PVE_NODE="pve"
export PVE_URL="192.168.1.148"
export DISCORD_TOKEN="tokenhere"
```
You do not need the `port` or `https://`.

Once that file exists run `direnv allow` to enable the autoloading of the `.envrc` file.

**Comment by LOn5Ghz** [comment]
i am going to try this now, thank you for taking the time to help

**Comment by LOn5Ghz** [comment]
also to clarify the "bot" folder is the root of the discord-proxmox-bot directory?

**Comment by markopolo123** [comment]
yeah, it is.

**Comment by LOn5Ghz** [comment]
got the same error, not sure why

**Comment by markopolo123** [comment]
start with basics:
```bash
curl -k -d 'username=root@pam' --data-urlencode 'password=xxxxxxxxx' https://192.168.1.148:8006/api2/json/access/ticket
```
does that return a ticket?

**Comment by LOn5Ghz** [comment]
yes, i get stuck after this, i got to the proxmox api already

**Comment by LOn5Ghz** [comment]
also need to stop ticket expiration

**Comment by markopolo123** [comment]
make sure that you've put the config from this:
```bash
config_data = {
"hostname": f'{os.getenv("[https://192.168.1.148:8006/#")}](https://192.168.1.148:8006/#%22)%7D)',
"username": f'{os.getenv("root@pam")}',
"password": f'{os.getenv("passwdhere")}',
"node": f'{os.getenv("pve")}',
"vm_id": f'{os.getenv("101")}',
}
```
back to this: 
```bash
config_data = {
    "hostname": f'{os.getenv("PVE_URL")}',
    "username": f'{os.getenv("PVE_USERNAME")}',
    "password": f'{os.getenv("PVE_PASSWORD")}',
    "node": f'{os.getenv("PVE_NODE")}',
    "vm_id": f'{os.getenv("VMID")}',
}
```
once you are confident that is the case, 
check your variables are loaded:
```bash
env | grep 'PVE'

```

then try rerunning the script:
```bash
# run the bot:
poetry run python main.py
```

**Comment by LOn5Ghz** [comment]
yes , i see loaded variables.

**Comment by markopolo123** [comment]
what error are you getting? be careful to not share your passwords etc ;)

**Comment by LOn5Ghz** [comment]
raceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://[https://192.168.1.148:8006/]:8006/api2/json/access/ticket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/discord-proxmox-bot/main.py", line 91, in status
    vm = ProxmoxVM(config)
  File "/home/pi/discord-proxmox-bot/main.py", line 26, in __init__
    self.proxmox = proxmoxer.ProxmoxAPI(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/core.py", line 210, in __init__
    self._backend = importlib.import_module(f".backends.{backend}", "proxmoxer").Backend(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 302, in __init__
    self.auth = ProxmoxHTTPAuth(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 59, in __init__
    self._get_new_tokens(password=password, otp=otp)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 70, in _get_new_tokens
    response_data = requests.post(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://[https://192.168.1.148:8006/]:8006/api2/json/access/ticket

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidURL: Failed to parse: https://[https://192.168.1.148:8006/]:8006/api2/json/access/ticket

**Comment by LOn5Ghz** [comment]
wondering if http(s) is causing any issues?

**Comment by LOn5Ghz** [comment]
wait that shouldnt even be there

**Comment by markopolo123** [comment]
```
urllib3.exceptions.LocationParseError: Failed to parse: https://[https://192.168.1.148:8006/]:8006/api2/json/access/ticket
```
There is a problem with your URL, looks like you've got it set as `https://192.168.1.148:8006/` when it should be `192.168.1.148`. The library takes care of the `https://` and `8006` for you ;)

**Comment by LOn5Ghz** [comment]
i have no https in sight

**Comment by LOn5Ghz** [comment]
export VMID="101"
export PVE_PASSWORD="NULL"
export PVE_USERNAME="root@pam"
export PVE_NODE="pve"
export PVE_URL="192.168.1.148"
export DISCORD_TOKEN="NULL"

**Comment by LOn5Ghz** [comment]
also switched my main.py to normal

**Comment by markopolo123** [comment]
what does `env | grep PVE_URL` return...
should look like this:
```
➜  env | grep PVE_URL
PVE_URL=192.168.1.148
```

**Comment by LOn5Ghz** [comment]
i fixed it, i had to export 192.168.1.148

**Comment by markopolo123** [comment]
happy botting :)

**Comment by LOn5Ghz** [comment]
oh god... can this manage lxc?

**Comment by markopolo123** [comment]
as written it does [qemu VMs](https://github.com/markopolo123/discord-proxmox-bot/blob/ad0ea0111791e454d45b41ee9738ef39f76b78c4/main.py#L33). 

[The docs](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/%7Bnode%7D/lxc/%7Bvmid%7D/status) for the lxc endpoint on the api look pretty promising, we should be able to change [line 33](https://github.com/markopolo123/discord-proxmox-bot/blob/ad0ea0111791e454d45b41ee9738ef39f76b78c4/main.py#L33)
to say

```
self.vm = self.proxmox.nodes(config.node).lxc(config.vm_id)
```

if you are super lucky that will just work ;)

**Comment by LOn5Ghz** [comment]
i Love you just so you are aware

**Comment by LOn5Ghz** [comment]
also how do i avoid ticket expiration? it wont expire as long as script is running because its logged in yes?

**Comment by LOn5Ghz** [comment]
also it would be cool if you sometime in the future added an option to execute scripts & commands

**Comment by LOn5Ghz** [comment]
also do i have to export QMID and not VMID

**Comment by markopolo123** [comment]
the proxmoxer library takes care of the tickets, it uses the username and password to refresh them.
continue exporting the variable as VMID, the script is just looking at it to get the ID, it doesn't actually know anything about the type of ID.

**Comment by LOn5Ghz** [comment]
it works. if i could pay you i would, id also support your work. thank you man.

**Comment by LOn5Ghz** [comment]
may run this off a vm on the server instead of a pi too , this is cool

**Comment by LOn5Ghz** [comment]
also keeps auto defaulting to this ? Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/discord-proxmox-bot/main.py", line 92, in status
    state = vm.status()
  File "/home/pi/discord-proxmox-bot/main.py", line 41, in status
    status_dict = self.vm.status.current.get()
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 500 Internal Server Error: Configuration file 'nodes/pve/lxc/100.conf' does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/pi/.cache/pypoetry/virtualenvs/discord-ct-5K29FBw_-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ResourceException: 500 Internal Server Error: Configuration file 'nodes/pve/lxc/100.conf' does not exist
i may have a fix

**Comment by markopolo123** [comment]
if running on a vm or lxc container, I'd use systemd to power it: 
note that you'll need to change the `execstart` line to point at your venv:

```
root@discord-ct:~# cat /etc/systemd/system/discord.service
[Unit]
Description=discord bot
After=network.target

[Service]
Type=simple
Restart=on-failure
User=root
ExecStart=/root/.cache/pypoetry/virtualenvs/discord-ct-M8M-TGhd-py3.11/bin/python3 main.py
WorkingDirectory=/root/discord-ct

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=discord

[Install]
WantedBy=multi-user.target
```

with the secrets in an override file so you no longer need the `.envrc`:
```
root@discord-ct:~# cat /etc/systemd/system/discord.service.d/override.conf

[Service]
Environment="VMID=111"
Environment="PVE_PASSWORD=passwordhere"
Environment="PVE_USERNAME=root@pam"
Environment="PVE_NODE=pve"
Environment="PVE_URL=pve.internal.sharpley.xyz"
Environment="DISCORD_TOKEN=tokenhere"
```

commands to ensure that it starts on boot etc. Be sure to prefix with sudo if you are not root user:

```bash
systemctl daemon-reload # needed after you change any systemd files
systemctl enable discord.service # so it starts on boot
systemctl start discord.service # get it running
```
`systemctl status discord.service` to check on it
